import AdminLayout from "../../layouts/AdminLayout";
import { Search, GitMerge, FileText, CheckCircle, XCircle } from "lucide-react";

const stats = [
  { label: "Total Matches", value: "12,842", detail: "+12% vs last month", icon: GitMerge, color: "text-blue-600 bg-blue-50 border-blue-100" },
  { label: "Pending Review", value: "452", detail: "Requires moderation", icon: FileText, color: "text-amber-600 bg-amber-50 border-amber-100" },
  { label: "Confirmed Matches", value: "8,102", detail: "98% system accuracy", icon: CheckCircle, color: "text-emerald-600 bg-emerald-50 border-emerald-100" },
  { label: "Rejected Matches", value: "4,288", detail: "False alarms flagged", icon: XCircle, color: "text-rose-600 bg-rose-50 border-rose-100" },
];

const tabs = ["All", "Lost Items", "Found Items"];

const matches = [
  {
    id: "842",
    left: { label: "Lost Wallet", sub: "ID: LP-102" },
    right: { label: "Found Wallet", sub: "ID: FP-550" },
    similarity: "94% Confidence",
    date: "Oct 24, 2023",
  },
  {
    id: "843",
    left: { label: "Lost Wallet", sub: "ID: LP-102" },
    right: { label: "Found Wallet", sub: "ID: FP-550" },
    similarity: "92% Confidence",
    date: "Oct 24, 2023",
  },
];

function MatchVerification() {
  return (
    <AdminLayout>
      <div className="mx-auto max-w-7xl space-y-6">
        {/* Header */}
        <section className="rounded-3xl border border-slate-200/50 bg-white/80 p-6 md:p-8 text-slate-900 shadow-sm backdrop-blur-md">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.24em] text-blue-600">
                Findora Admin
              </p>
              <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Matching Posts</h1>
              <p className="mt-2 text-sm text-slate-500 max-w-2xl">
                Review and manage possible matches generated by the system AI.
              </p>
            </div>

            <div className="relative w-full sm:w-64">
              <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <input
                type="search"
                placeholder="Search ID, finder, owner..."
                className="w-full rounded-full border border-slate-200 bg-white py-2.5 pl-11 pr-4 text-xs text-slate-950 placeholder-slate-400 outline-none transition focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
              />
            </div>
          </div>
        </section>

        {/* Stats Grid */}
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {stats.map((stat) => {
            const Icon = stat.icon;
            return (
              <div 
                key={stat.label} 
                className="rounded-2xl border border-slate-200/50 bg-white/80 p-5 shadow-xs backdrop-blur-md flex items-start gap-4"
              >
                <div className={`rounded-xl p-2.5 border ${stat.color}`}>
                  <Icon className="h-5 w-5" />
                </div>
                <div>
                  <p className="text-xs font-bold uppercase tracking-wider text-slate-400">{stat.label}</p>
                  <p className="mt-1 text-2xl font-bold text-slate-950">{stat.value}</p>
                  <p className="mt-1 text-[10px] text-slate-500">{stat.detail}</p>
                </div>
              </div>
            );
          })}
        </div>

        {/* Main List Table */}
        <section className="rounded-3xl border border-slate-200/50 bg-white/80 p-5 md:p-6 shadow-sm backdrop-blur-md">
          <div className="flex items-center justify-between border-b border-slate-100 pb-5">
            <div className="flex flex-wrap gap-2 text-xs font-semibold">
              {tabs.map((tab) => (
                <button
                  key={tab}
                  className={`rounded-full px-4 py-1.5 transition ${
                    tab === "All"
                      ? "bg-blue-600 text-white"
                      : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                  }`}
                >
                  {tab}
                </button>
              ))}
            </div>
          </div>

          <div className="mt-5 overflow-x-auto">
            <table className="w-full min-w-[900px] border-collapse text-left text-xs">
              <thead>
                <tr>
                  <th className="pb-4 font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100">Match ID</th>
                  <th className="pb-4 pr-4 font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100">Lost Report A</th>
                  <th className="pb-4 pr-4 font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100">Found Report B</th>
                  <th className="pb-4 pr-4 font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100">Similarity</th>
                  <th className="pb-4 pr-4 font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100">Detection Date</th>
                  <th className="pb-4 font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {matches.map((match) => (
                  <tr key={match.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="py-4 font-semibold text-slate-700">#MCH-{match.id}</td>
                    <td className="py-4 pr-4">
                      <div className="rounded-xl border border-slate-200 bg-white p-3 shadow-xs">
                        <p className="font-bold text-slate-900">{match.left.label}</p>
                        <p className="mt-1 text-[10px] text-slate-400">{match.left.sub}</p>
                      </div>
                    </td>
                    <td className="py-4 pr-4">
                      <div className="rounded-xl border border-slate-200 bg-white p-3 shadow-xs">
                        <p className="font-bold text-slate-900">{match.right.label}</p>
                        <p className="mt-1 text-[10px] text-slate-400">{match.right.sub}</p>
                      </div>
                    </td>
                    <td className="py-4 pr-4">
                      <div className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700 uppercase tracking-wide">
                        <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                        {match.similarity}
                      </div>
                    </td>
                    <td className="py-4 pr-4 text-slate-500">{match.date}</td>
                    <td className="py-4 text-right">
                      <button className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-slate-600 hover:bg-slate-50 transition">
                        Compare Details
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Breakdown section */}
        <section className="rounded-3xl border border-slate-200/50 bg-white/80 p-5 md:p-6 shadow-sm backdrop-blur-md">
          <div className="grid gap-6 lg:grid-cols-5">
            {/* Step Analysis */}
            <div className="lg:col-span-2 rounded-2xl border border-slate-100 bg-slate-50/50 p-5 flex flex-col justify-between">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Match Analysis</span>
                <h4 className="text-xl font-bold text-slate-950 mt-1">Review ID: 842</h4>
              </div>

              <div className="mt-6 space-y-4">
                {['Generated', 'Review', 'Verify', 'Resolve'].map((step, index) => (
                  <div key={step} className="flex items-center gap-3.5 rounded-xl border border-slate-200 bg-white p-3 shadow-xs">
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-50 text-xs font-bold text-blue-600">{index + 1}</div>
                    <div>
                      <p className="text-xs font-bold text-slate-900">{step}</p>
                      <p className="text-[9px] text-slate-400">Workflow stage details</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Split Comparison Preview */}
            <div className="lg:col-span-3 rounded-2xl border border-slate-100 bg-slate-50/50 p-5 space-y-4">
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Original Post</p>
                  <div className="mt-3 text-center">
                    <div className="mx-auto mb-3 h-28 w-28 rounded-lg bg-slate-100 border border-slate-100 flex items-center justify-center text-xs text-slate-400 font-medium">Image Preview</div>
                    <p className="font-bold text-slate-900 text-sm">Montblanc Wallet</p>
                    <p className="mt-0.5 text-[10px] text-slate-400">Lost at Central Park</p>
                  </div>
                </div>

                <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Suggested Match</p>
                  <div className="mt-3 text-center">
                    <div className="mx-auto mb-3 h-28 w-28 rounded-lg bg-slate-100 border border-slate-100 flex items-center justify-center text-xs text-slate-400 font-medium">Image Preview</div>
                    <p className="font-bold text-slate-900 text-sm">Black Leather Wallet</p>
                    <p className="mt-0.5 text-[10px] text-slate-400">Found near 5th Ave</p>
                  </div>
                </div>
              </div>

              <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-xs">
                <p className="text-[10px] font-bold uppercase tracking-wider text-slate-450 text-slate-400">Matching Threshold Confidence</p>
                <div className="mt-3.5 h-2 overflow-hidden rounded-full bg-slate-100">
                  <div className="h-2 w-11/12 rounded-full bg-emerald-500" />
                </div>
                <p className="mt-2 text-xs font-semibold text-slate-650 text-slate-600">94% similarity score detected</p>
              </div>

              <div className="space-y-3.5">
                <textarea
                  rows={3}
                  placeholder="Add internal review notes here..."
                  className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-xs text-slate-950 placeholder-slate-400 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                />
                
                <div className="flex gap-2.5">
                  <button className="flex-1 rounded-full border border-slate-250 border-slate-200 bg-white px-5 py-2.5 text-xs font-semibold text-slate-600 hover:bg-slate-50 transition">
                    Reject Match
                  </button>
                  <button className="flex-1 rounded-full bg-blue-600 px-5 py-2.5 text-xs font-semibold text-white shadow-sm hover:bg-blue-700 transition-all">
                    Confirm Match
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </AdminLayout>
  );
}

export default MatchVerification;
