import AdminLayout from "../../layouts/AdminLayout";

const stats = [
  { label: "Total Matches", value: "12,842", detail: "+12%" },
  { label: "Pending Review", value: "452", detail: "Ongoing" },
  { label: "Confirmed Matches", value: "8,102", detail: "98% acc." },
  { label: "Rejected Matches", value: "4,288", detail: "-2%" },
];

const tabs = ["All", "Lost Items", "Found Items"];

const matches = [
  {
    id: "842",
    left: { label: "Lost Wallet", sub: "ID: LP-102" },
    right: { label: "Found Wallet", sub: "ID: FP-550" },
    similarity: "94% Confidence",
    date: "Oct 24, 2023",
  },
  {
    id: "843",
    left: { label: "Lost Wallet", sub: "ID: LP-102" },
    right: { label: "Found Wallet", sub: "ID: FP-550" },
    similarity: "92% Confidence",
    date: "Oct 24, 2023",
  },
];

function MatchVerification() {
  return (
    <AdminLayout>
      <div className="mx-auto max-w-7xl space-y-8">
        <section className="rounded-[2rem] bg-slate-950/95 p-8 text-white shadow-2xl shadow-slate-900/40">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.35em] text-sky-300/80">
                Findora Admin
              </p>
              <h1 className="mt-4 text-4xl font-semibold">Matching Posts</h1>
              <p className="mt-3 max-w-2xl text-sm text-slate-300">
                Review and manage possible matches generated by the system AI.
              </p>
            </div>

            <div className="relative w-full max-w-sm">
              <span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-500">??</span>
              <input
                type="search"
                placeholder="Search ID, Category, User..."
                className="w-full rounded-full border border-slate-800 bg-slate-900/90 py-3 pl-12 pr-4 text-sm text-slate-100 outline-none focus:border-blue-500"
              />
            </div>
          </div>
        </section>

        <div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">
          {stats.map((stat) => (
            <div key={stat.label} className="rounded-[1.75rem] bg-blue-950/95 p-6 shadow-xl shadow-slate-900/20">
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-400">{stat.label}</p>
              <p className="mt-4 text-3xl font-semibold text-white">{stat.value}</p>
              <p className="mt-3 text-sm text-slate-400">{stat.detail}</p>
            </div>
          ))}
        </div>

        <section className="rounded-[2rem] bg-slate-950/95 p-6 shadow-2xl shadow-slate-900/40">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-wrap gap-2">
              {tabs.map((tab) => (
                <button
                  key={tab}
                  className={`rounded-full px-4 py-2 text-xs font-semibold transition ${
                    tab === "All"
                      ? "bg-blue-600 text-white"
                      : "border border-slate-800 bg-slate-900/80 text-slate-300 hover:bg-slate-800"
                  }`}
                >
                  {tab}
                </button>
              ))}
            </div>
          </div>

          <div className="mt-6 overflow-x-auto">
            <table className="w-full min-w-[920px] border-collapse text-left text-sm text-slate-300">
              <thead>
                <tr>
                  <th className="pb-4 pr-6 text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Match ID</th>
                  <th className="pb-4 pr-6 text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Post A</th>
                  <th className="pb-4 pr-6 text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Post B</th>
                  <th className="pb-4 pr-6 text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Similarity</th>
                  <th className="pb-4 pr-6 text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Date</th>
                  <th className="pb-4 text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {matches.map((match) => (
                  <tr key={match.id} className="border-t border-slate-800">
                    <td className="py-5 pr-6 font-semibold text-slate-100">{match.id}</td>
                    <td className="py-5 pr-6">
                      <div className="rounded-3xl border border-slate-800 bg-slate-900/90 p-4">
                        <p className="font-semibold text-white">{match.left.label}</p>
                        <p className="mt-2 text-xs text-slate-500">{match.left.sub}</p>
                      </div>
                    </td>
                    <td className="py-5 pr-6">
                      <div className="rounded-3xl border border-slate-800 bg-slate-900/90 p-4">
                        <p className="font-semibold text-white">{match.right.label}</p>
                        <p className="mt-2 text-xs text-slate-500">{match.right.sub}</p>
                      </div>
                    </td>
                    <td className="py-5 pr-6">
                      <div className="inline-flex min-w-[120px] items-center gap-3 rounded-full bg-slate-900/70 px-3 py-2 text-xs font-semibold text-slate-300">
                        <div className="h-2.5 w-2.5 rounded-full bg-emerald-400" />
                        {match.similarity}
                      </div>
                    </td>
                    <td className="py-5 pr-6 text-slate-300">{match.date}</td>
                    <td className="py-5 text-slate-300">
                      <button className="rounded-full bg-slate-900/80 px-3 py-2 text-slate-300 transition hover:bg-slate-800 hover:text-white">View</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="rounded-[2rem] bg-slate-950/95 p-6 shadow-2xl shadow-slate-900/40">
          <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
            <div className="rounded-[1.75rem] bg-slate-900/90 p-6">
              <div className="flex items-center justify-between gap-4">
                <div>
                  <p className="text-sm uppercase tracking-[0.24em] text-slate-400">Match Analysis</p>
                  <p className="mt-2 text-xl font-semibold text-white">ID: 842</p>
                </div>
                <span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-300">High Confidence</span>
              </div>

              <div className="mt-8 grid gap-4 sm:grid-cols-4">
                {['Generated', 'Review', 'Verify', 'Resolve'].map((step, index) => (
                  <div key={step} className="space-y-3 rounded-3xl bg-slate-950/80 p-4 text-center">
                    <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-slate-800 text-sm font-semibold text-white">{index + 1}</div>
                    <p className="text-xs uppercase tracking-[0.24em] text-slate-400">{step}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="rounded-[1.75rem] bg-slate-900/90 p-6">
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-3xl bg-slate-950/95 p-4">
                  <p className="text-sm font-semibold text-slate-300">Original Post</p>
                  <div className="mt-4 rounded-[1.5rem] bg-slate-800 p-4 text-center text-white">
                    <div className="mx-auto mb-4 h-40 w-40 rounded-3xl bg-slate-900" />
                    <p className="font-semibold">Montblanc Wallet</p>
                    <p className="mt-1 text-xs text-slate-500">Lost at Central Park</p>
                  </div>
                </div>
                <div className="rounded-3xl bg-slate-950/95 p-4">
                  <p className="text-sm font-semibold text-slate-300">Suggested Match</p>
                  <div className="mt-4 rounded-[1.5rem] bg-slate-800 p-4 text-center text-white">
                    <div className="mx-auto mb-4 h-40 w-40 rounded-3xl bg-slate-900" />
                    <p className="font-semibold">Black Leather Wallet</p>
                    <p className="mt-1 text-xs text-slate-500">Found near 5th Ave</p>
                  </div>
                </div>
              </div>

              <div className="mt-6 rounded-[1.5rem] bg-slate-950/90 p-4">
                <p className="text-sm uppercase tracking-[0.24em] text-slate-400">Matching</p>
                <div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800">
                  <div className="h-2 w-11/12 rounded-full bg-emerald-400" />
                </div>
                <p className="mt-3 text-sm text-slate-300">94% similarity</p>
              </div>

              <div className="mt-6 space-y-4">
                <textarea
                  rows={4}
                  placeholder="Add internal review notes here..."
                  className="w-full rounded-[1.5rem] border border-slate-800 bg-slate-900/95 p-4 text-sm text-slate-100 outline-none focus:border-blue-500"
                />
                <div className="flex flex-wrap gap-3">
                  <button className="rounded-full border border-slate-800 px-5 py-3 text-sm font-semibold text-slate-300 hover:bg-slate-800">
                    Reject Match
                  </button>
                  <button className="rounded-full bg-gradient-to-r from-blue-600 via-cyan-500 to-violet-500 px-5 py-3 text-sm font-semibold text-white hover:opacity-95">
                    Confirm Match
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </AdminLayout>
  );
}

export default MatchVerification;
